name: Docker CI/CD Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build csharp
        run: |
          docker build ./HelloWorld -t clubforge/cicddemo
