name: Docker CI/CD Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: |
        docker build ./HelloWorld -t ghcr.io/clubforge/helloworld:latest